Fix the possibility to override the logout request uri (end_session endpoint)
ch4mpy/spring-addons pull request #195
Opened 2024-03-11 11:55 UTC by kriszman

Came across this project after reading an article on Baeldung who linked it for good reason.
It's really amazing and I'm really glad I stumbled across it as it's more than helpful setting up and generally getting into oidc and authentication.
However, I had some issues trying to override the end session endpoint provided by the OP discovery as described in the README. When specifying an alternative url in the application properties (oauth2-logout) this url isn't recognized, so I tried to adapt the corresponding parts. Hope this makes sense, thx.

2024-03-11 16:56 UTC, ch4mpy requested changes
Thks for this PR.

Please restore the ability to disable RP-Initiated Logout from properties, I think that the missing argument you found in th logout success-handler is enough to fix your issue.

2024-03-11 16:56 UTC, ch4mpy commented on spring-addons-starter-oidc/src/main/java/com/c4_soft/springaddons/security/oidc/starter/SpringAddonsOAuth2LogoutRequestUriBuilder.java
> -        if (logoutProps.map(OAuth2LogoutProperties::isEnabled).orElse(false)) {
I think that this test should be kept: as [documented on the property](https://github.com/ch4mpy/spring-addons/blob/a2010649edf33a6b6bd5b7974f9eb7b1b0df55e9/spring-addons-starter-oidc/src/main/java/com/c4_soft/springaddons/security/oidc/starter/properties/SpringAddonsOidcClientProperties.java#L212) the aim is to give the opportunity to disable RP-Initiated Logout (keep the user session on the authorization server) and skip directly to the post-logout URI.

2024-03-11 16:56 UTC, ch4mpy commented on spring-addons-starter-oidc/src/main/java/com/c4_soft/springaddons/security/oidc/starter/synchronised/client/SpringAddonsLogoutSuccessHandler.java
> +        this.redirectStrategy.sendRedirect(request, response, determineTargetUrl(request, response, authentication));
:thumbsup:

2024-03-11 16:56 UTC, ch4mpy commented on spring-addons-starter-oidc/src/main/java/com/c4_soft/springaddons/security/oidc/starter/synchronised/client/SpringAddonsLogoutSuccessHandler.java
> +        this.redirectStrategy.sendRedirect(request, response, determineTargetUrl(request, response, authentication));
:thumbsup:

2024-03-11 17:36 UTC, ch4mpy commented on spring-addons-starter-oidc/src/main/java/com/c4_soft/springaddons/security/oidc/starter/SpringAddonsOAuth2LogoutRequestUriBuilder.java
> -        if (logoutProps.map(OAuth2LogoutProperties::isEnabled).orElse(false)) {
True, it should be negated.

As a side note, I wonder how could the [resource-server_with_ui tutorial](https://github.com/ch4mpy/spring-addons/tree/master/samples/tutorials/resource-server_with_ui) ever work...

2024-03-11 17:40 UTC, merged

2024-03-11 17:42 UTC, ch4mpy commented
@kriszman thank you again for your investigations and fix.

I'll release this patch in the next 8-10 hours and will ping you when the new version is available from maven-central.

2024-03-11 17:48 UTC, kriszman commented
> @kriszman thank you again for your investigations and fix.
> 
> I'll release this patch in the next 8-10 hours (don't have the required GPG keys at hand) and will ping you when the new version is available from maven-central.

no worries, it's been really a small issue, happy I could assist a little. Thank you for this amazing library, hope it keeps on going... and thx for keeping me posted 👍

2024-03-12 01:16 UTC, ch4mpy commented
@kriszman the `7.6.6` is available from maven-central. It contains your fix.

2024-03-12 07:27 UTC, ch4mpy commented
@kriszman the version to use is actually `7.6.7`. There was still a small issue with the condition to de-activate RP-Initiated Logout: in case where logout properties are not provided at all, we want to keep RP-Initiated Logout => de-activation "not true"

2024-03-12 07:56 UTC, kriszman commented
> @kriszman the version to use is actually `7.6.7`. There was still a small issue with the condition to de-activate RP-Initiated Logout: in case where logout properties are not provided at all, we want to keep RP-Initiated Logout => de-activation "not true"

@ch4mpy I see, seems like I've been too focused on my use case, sorry for the inconvenience and thx for the fast feedback and fix!